version: '3.9'

services:

  mongo:
    image: mongo:4.2.5
    ports:
      - '27017:27017'

  server:
    build: .
    ports: 
      - "8080:8080"
    volumes:
      - .:/root
    environment:
      FLASK_ENV: development
