version: '3.3'
services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
  mongo:
    image: mongo:4.2.5
    expose: # Use 'expose' instead of 'ports' to add security
    - '27017'
  app:
    build: .
    volumes:
      - .:/root
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - '8080:8080'