version: '3.3'
services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    # COMMENT OUT THE NEXT 3 LINES IF YOU WANT TO USE LOCALHOST   
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Ensuring SSL certificates are accessible
    restart: unless-stopped

  mongo:
    image: mongo:4.2.5
    expose:
      - '27017'  # Makes MongoDB available only to linked services

  app:
    build: .
    volumes:
      - .:/root 
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - '8080:8080'
    depends_on:
      - mongo
